[package]
name = "osveijer-task-13"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.2"
vecmath = "1.0.0"
rand = "0.8.4"
rayon = "1.5.1"